# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://:redis_password@pub-redis-11137.us-west-2-1.1.ec2.garantiadata.com:11137

development:
  adapter: async

test:
  adapter: async
